# Generated by Django 3.1.3 on 2021-04-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_code', models.BigIntegerField()),
                ('authenticated', models.BooleanField(default=False)),
                ('client_id', models.IntegerField()),
                ('user_code', models.IntegerField()),
                ('user_code_lifetime', models.IntegerField()),
                ('verification_uri', models.CharField(max_length=50)),
                ('verification_uri_complete', models.CharField(max_length=100)),
                ('interval', models.IntegerField(default=5)),
                ('scope', models.CharField(blank=True, max_length=20, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('access_token', models.IntegerField(blank=True, null=True)),
                ('access_token_creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('access_token_lifetime', models.IntegerField(default=604800)),
                ('refresh_token', models.IntegerField(blank=True, null=True)),
                ('request_denied', models.BooleanField(default=False)),
                ('device_name', models.CharField(default='', max_length=40)),
                ('timeout', models.BooleanField(default=False)),
                ('service_unavailable', models.BooleanField(default=False)),
            ],
        ),
    ]
